from typing import Callable, Generic, Protocol, TypeVar

Entity = TypeVar("Entity")


class Repository(Protocol, Generic[Entity]):
    def insert(self, entity: Entity) -> None: ...
    def delete(self, id: str) -> None: ...
    def update(self, entity: Entity) -> None: ...
    def get(self, id) -> Entity | None: ...
    def list(self) -> list[Entity]: ...
    def mutate(self, id: str, fn: Callable[[Entity], Entity]) -> None: ...
